apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    isDefault: true
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: default
      username: default
      tlsSkipVerify: true
      dialTimeout: 10
      queryTimeout: 60
    secureJsonData:
      password: secret
    version: 1
    editable: true